export const FETCH_DOGOS_START = 'FETCH_DOGOS_START';
export const FETCH_DOGOS_SUCCESS = 'FETCH_DOGOS_SUCCESS';
export const FETCH_DOGOS_FAIL = 'FETCH_DOGOS_FAIL';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE-SUCCESS';
export const ADD_FAVORITE_FAIL = 'ADD_FAVORITE_FAIL';

export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAIL = 'FETCH_FAVORITES_FAIL';

export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const DELETE_FAVORITE_SUCCESS = 'DELETE_FAVORITE_SUCCESS';
export const DELETE_FAVORITE_FAIL = 'DELETE_FAVORITE_FAIL';

export const QUEUE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const DEQUEUE_NOTIFICATION = 'DISPOSE_NOTIFICATION';

export const AUTH_INIT_EXISTING_USER = 'AUTH_INIT_EXISTING_USER';
export const AUTH_INIT_NO_USER = 'AUTH_INIT_NO_USER';

export const AUTH_USER_LOGIN_START = 'AUTH_USER_LOGIN_START';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_USER_LOGIN_FAIL = 'AUTH_USER_LOGIN_FAIL';

export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';
